POST http://localhost:3000/pessoa
Accept: application/json
Content-Type: application/json

{
    //"name":"a",
    //"age":"48"
}


###

POST http://localhost:3000/login
Accept: application/json
Content-Type: application/json

{
    "email":"balduino@sapo.ao",
    "password":"fernando"
}
    